var _gbSubDictionary = {
	OrderDetail : {
		_rightOnTable: { },
		_titleName: "OrderDetail",
		_id: "OrderDetail",
		_className: "display",
		_listReports: [{}],
		_listSelfTables: [
			{ AjaxObj: { a: "fGetOrderDetail", _f: "*", _gb: "", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" },
			{ AjaxObj: { a: "fGetOrderDetail", _f: "Id,ServicesID,OrderID,StaffID,Price,TIP,NumServices,Discount,Total,Coupon,Note,isActive,isValid,isCreatedDate,isUpdatedDate,isPartFull", _gb: "", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" },
			{ AjaxObj: { a: "fGetOrderDetail", _f: "Id,ServicesID,OrderID,StaffID,Price,TIP,NumServices,Discount,Total,Coupon,Note,isActive,isValid,isCreatedDate,isUpdatedDate,isPartFull", _gb: "", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" },
		],
		_listRefTables: [
			{ field: "ServicesID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetServices", c: { }, _f: "Id,Name,Code", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } },
			{ field: "OrderID", mergename: [1], objAjax: { AjaxObj: { a: "fGetOrders", c: { }, _f: "Id,Id", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } },
			{ field: "StaffID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetStaff", c: { }, _f: "Id,Name,Phone", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }
		],
		_fieldsList: [
			/*0*/{ field: "Id", name: "Identify", create: true, edit: true, list: true, type: "bigint",  expandtype:"hidden" },
			/*1*/{ field: "ServicesID", name: "ServicesID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "ServicesID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetServices", c: { }, _f: "Id,Name,Code", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*2*/{ field: "OrderID", name: "OrderID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "OrderID", mergename: [1], objAjax: { AjaxObj: { a: "fGetOrders", c: { }, _f: "Id,Id", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*3*/{ field: "StaffID", name: "StaffID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "StaffID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetStaff", c: { }, _f: "Id,Name,Phone", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*4*/{ field: "Price", name: "Price", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*5*/{ field: "TIP", name: "TIP", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*6*/{ field: "NumServices", name: "NumServices", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*7*/{ field: "Discount", name: "Discount", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*8*/{ field: "Total", name: "Total", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*9*/{ field: "Coupon", name: "Coupon", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*10*/{ field: "Note", name: "Note", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*11*/{ field: "isActive", name: "isActive", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*12*/{ field: "isValid", name: "isValid", create: false, edit: false, list: false, type: "int",  expandtype:"" },
			/*13*/{ field: "isCreatedDate", name: "isCreateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*14*/{ field: "isUpdatedDate", name: "isUpdateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*15*/{ field: "isPartFull", name: "isPartFull", create: false, edit: false, list: false, type: "string",  expandtype:"" }
		],
		_fieldsReport: [
			/*0*/{ field: "Id", name: "Identify", create: true, edit: true, list: true, type: "bigint",  expandtype:"hidden" },
			/*1*/{ field: "ServicesID", name: "ServicesID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "ServicesID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetServices", c: { }, _f: "Id,Name,Code", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*2*/{ field: "OrderID", name: "OrderID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "OrderID", mergename: [1], objAjax: { AjaxObj: { a: "fGetOrders", c: { }, _f: "Id,Id", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*3*/{ field: "StaffID", name: "StaffID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "StaffID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetStaff", c: { }, _f: "Id,Name,Phone", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*4*/{ field: "Price", name: "Price", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*5*/{ field: "TIP", name: "TIP", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*6*/{ field: "NumServices", name: "NumServices", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*7*/{ field: "Discount", name: "Discount", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*8*/{ field: "Total", name: "Total", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*9*/{ field: "Coupon", name: "Coupon", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*10*/{ field: "Note", name: "Note", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*11*/{ field: "isActive", name: "isActive", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*12*/{ field: "isValid", name: "isValid", create: false, edit: false, list: false, type: "int",  expandtype:"" },
			/*13*/{ field: "isCreatedDate", name: "isCreateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*14*/{ field: "isUpdatedDate", name: "isUpdateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*15*/{ field: "isPartFull", name: "isPartFull", create: false, edit: false, list: false, type: "string",  expandtype:"" }
		],
		_fieldsSearch: [
			/*0*/{ field: "Id", name: "Identify", create: true, edit: true, list: true, type: "bigint",  expandtype:"hidden" },
			/*1*/{ field: "ServicesID", name: "ServicesID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "ServicesID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetServices", c: { }, _f: "Id,Name,Code", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*2*/{ field: "OrderID", name: "OrderID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "OrderID", mergename: [1], objAjax: { AjaxObj: { a: "fGetOrders", c: { }, _f: "Id,Id", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*3*/{ field: "StaffID", name: "StaffID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "StaffID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetStaff", c: { }, _f: "Id,Name,Phone", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*4*/{ field: "Price", name: "Price", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*5*/{ field: "TIP", name: "TIP", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*6*/{ field: "NumServices", name: "NumServices", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*7*/{ field: "Discount", name: "Discount", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*8*/{ field: "Total", name: "Total", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*9*/{ field: "Coupon", name: "Coupon", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*10*/{ field: "Note", name: "Note", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*11*/{ field: "isActive", name: "isActive", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*12*/{ field: "isValid", name: "isValid", create: false, edit: false, list: false, type: "int",  expandtype:"" },
			/*13*/{ field: "isCreatedDate", name: "isCreateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*14*/{ field: "isUpdatedDate", name: "isUpdateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*15*/{ field: "isPartFull", name: "isPartFull", create: false, edit: false, list: false, type: "string",  expandtype:"" }
		],
		_editform: [
			{ row: [0, 1], style: [".col-md-2", ".col-md-4"] },
			{ row: [2, 3], style: [".col-md-2", ".col-md-4"] },
			{ row: [4, 5], style: [".col-md-2", ".col-md-4"] },
			{ row: [6, 7], style: [".col-md-2", ".col-md-4"] },
			{ row: [8, 9], style: [".col-md-2", ".col-md-4"] },
			{ row: [10, 11], style: [".col-md-2", ".col-md-4"] },
			{ row: [12, 13], style: [".col-md-2", ".col-md-4"] },
			{ row: [14, 15], style: [".col-md-2", ".col-md-4"] },

		],
		_searchform: [
			{ row: [0, 1], style: [".col-md-2", ".col-md-4"] },
			{ row: [2, 3], style: [".col-md-2", ".col-md-4"] },
			{ row: [4, 5], style: [".col-md-2", ".col-md-4"] },
			{ row: [6, 7], style: [".col-md-2", ".col-md-4"] },
			{ row: [8, 9], style: [".col-md-2", ".col-md-4"] },
			{ row: [10, 11], style: [".col-md-2", ".col-md-4"] },
			{ row: [12, 13], style: [".col-md-2", ".col-md-4"] },
			{ row: [14, 15], style: [".col-md-2", ".col-md-4"] },

		],
		_updateform: [
			{ row: [0, 1], style: [".col-md-2", ".col-md-4"] },
			{ row: [2, 3], style: [".col-md-2", ".col-md-4"] },
			{ row: [4, 5], style: [".col-md-2", ".col-md-4"] },
			{ row: [6, 7], style: [".col-md-2", ".col-md-4"] },
			{ row: [8, 9], style: [".col-md-2", ".col-md-4"] },
			{ row: [10, 11], style: [".col-md-2", ".col-md-4"] },
			{ row: [12, 13], style: [".col-md-2", ".col-md-4"] },
			{ row: [14, 15], style: [".col-md-2", ".col-md-4"] },

		],
	},
	Services : {
		_rightOnTable: { },
		_titleName: "Services",
		_id: "Services",
		_className: "display",
		_listReports: [{}],
		_listSelfTables: [
			{ AjaxObj: { a: "fGetServices", _f: "*", _gb: "", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" },
			{ AjaxObj: { a: "fGetServices", _f: "Id,BusinessID,CategoryID,Name,Price,Duration,NumStaffDoIt,isActive,isValid,isCreatedDate,isUpdatedDate,isPartFull", _gb: "", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" },
			{ AjaxObj: { a: "fGetServices", _f: "Id,BusinessID,CategoryID,Name,Price,Duration,NumStaffDoIt,isActive,isValid,isCreatedDate,isUpdatedDate,isPartFull", _gb: "", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" },
		],
		_listRefTables: [
			{ field: "BusinessID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetBusiness", c: { }, _f: "Id,Name,Phone", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } },
			{ field: "CategoryID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetCategorys", c: { }, _f: "Id,Name,Code", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }
		],
		_fieldsList: [
			/*0*/{ field: "Id", name: "Identify", create: true, edit: true, list: true, type: "bigint",  expandtype:"hidden" },
			/*1*/{ field: "BusinessID", name: "BusinessID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "BusinessID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetBusiness", c: { }, _f: "Id,Name,Phone", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*2*/{ field: "CategoryID", name: "CategoryID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "CategoryID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetCategorys", c: { }, _f: "Id,Name,Code", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*3*/{ field: "Name", name: "Name", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*4*/{ field: "Price", name: "Price", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*5*/{ field: "Duration", name: "Duration", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*6*/{ field: "NumStaffDoIt", name: "NumStaffDoIt", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*7*/{ field: "isActive", name: "isActive", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*8*/{ field: "isValid", name: "isValid", create: false, edit: false, list: false, type: "int",  expandtype:"" },
			/*9*/{ field: "isCreatedDate", name: "isCreateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*10*/{ field: "isUpdatedDate", name: "isUpdateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*11*/{ field: "isPartFull", name: "isPartFull", create: false, edit: false, list: false, type: "string",  expandtype:"" }
		],
		_fieldsReport: [
			/*0*/{ field: "Id", name: "Identify", create: true, edit: true, list: true, type: "bigint",  expandtype:"hidden" },
			/*1*/{ field: "BusinessID", name: "BusinessID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "BusinessID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetBusiness", c: { }, _f: "Id,Name,Phone", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*2*/{ field: "CategoryID", name: "CategoryID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "CategoryID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetCategorys", c: { }, _f: "Id,Name,Code", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*3*/{ field: "Name", name: "Name", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*4*/{ field: "Price", name: "Price", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*5*/{ field: "Duration", name: "Duration", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*6*/{ field: "NumStaffDoIt", name: "NumStaffDoIt", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*7*/{ field: "isActive", name: "isActive", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*8*/{ field: "isValid", name: "isValid", create: false, edit: false, list: false, type: "int",  expandtype:"" },
			/*9*/{ field: "isCreatedDate", name: "isCreateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*10*/{ field: "isUpdatedDate", name: "isUpdateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*11*/{ field: "isPartFull", name: "isPartFull", create: false, edit: false, list: false, type: "string",  expandtype:"" }
		],
		_fieldsSearch: [
			/*0*/{ field: "Id", name: "Identify", create: true, edit: true, list: true, type: "bigint",  expandtype:"hidden" },
			/*1*/{ field: "BusinessID", name: "BusinessID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "BusinessID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetBusiness", c: { }, _f: "Id,Name,Phone", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*2*/{ field: "CategoryID", name: "CategoryID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "CategoryID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetCategorys", c: { }, _f: "Id,Name,Code", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*3*/{ field: "Name", name: "Name", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*4*/{ field: "Price", name: "Price", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*5*/{ field: "Duration", name: "Duration", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*6*/{ field: "NumStaffDoIt", name: "NumStaffDoIt", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*7*/{ field: "isActive", name: "isActive", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*8*/{ field: "isValid", name: "isValid", create: false, edit: false, list: false, type: "int",  expandtype:"" },
			/*9*/{ field: "isCreatedDate", name: "isCreateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*10*/{ field: "isUpdatedDate", name: "isUpdateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*11*/{ field: "isPartFull", name: "isPartFull", create: false, edit: false, list: false, type: "string",  expandtype:"" }
		],
		_editform: [
			{ row: [0, 1], style: [".col-md-2", ".col-md-4"] },
			{ row: [2, 3], style: [".col-md-2", ".col-md-4"] },
			{ row: [4, 5], style: [".col-md-2", ".col-md-4"] },
			{ row: [6, 7], style: [".col-md-2", ".col-md-4"] },
			{ row: [8, 9], style: [".col-md-2", ".col-md-4"] },
			{ row: [10, 11], style: [".col-md-2", ".col-md-4"] },

		],
		_searchform: [
			{ row: [0, 1], style: [".col-md-2", ".col-md-4"] },
			{ row: [2, 3], style: [".col-md-2", ".col-md-4"] },
			{ row: [4, 5], style: [".col-md-2", ".col-md-4"] },
			{ row: [6, 7], style: [".col-md-2", ".col-md-4"] },
			{ row: [8, 9], style: [".col-md-2", ".col-md-4"] },
			{ row: [10, 11], style: [".col-md-2", ".col-md-4"] },

		],
		_updateform: [
			{ row: [0, 1], style: [".col-md-2", ".col-md-4"] },
			{ row: [2, 3], style: [".col-md-2", ".col-md-4"] },
			{ row: [4, 5], style: [".col-md-2", ".col-md-4"] },
			{ row: [6, 7], style: [".col-md-2", ".col-md-4"] },
			{ row: [8, 9], style: [".col-md-2", ".col-md-4"] },
			{ row: [10, 11], style: [".col-md-2", ".col-md-4"] },

		],
	},
	Orders : {
		_rightOnTable: { },
		_titleName: "Orders",
		_id: "Orders",
		_className: "display",
		_listReports: [{}],
		_listSelfTables: [
			{ AjaxObj: { a: "fGetOrders", _f: "*", _gb: "", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" },
			{ AjaxObj: { a: "fGetOrders", _f: "Id,BusinessID,CustomerID,DateCheckIn,DateCheckOut,DateDeliveryInfo,DaySendInfo,RoomInfo,PersonReceiveInfo,StatusOrder,AnniversaryDay,RelationInfo,OcupationInfo,isActive,isValid,isCreatedDate,isUpdatedDate,isPartFull", _gb: "", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" },
			{ AjaxObj: { a: "fGetOrders", _f: "Id,BusinessID,CustomerID,DateCheckIn,DateCheckOut,DateDeliveryInfo,DaySendInfo,RoomInfo,PersonReceiveInfo,StatusOrder,AnniversaryDay,RelationInfo,OcupationInfo,isActive,isValid,isCreatedDate,isUpdatedDate,isPartFull", _gb: "", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" },
		],
		_listRefTables: [
			{ field: "BusinessID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetBusiness", c: { }, _f: "Id,Name,Phone", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } },
			{ field: "CustomerID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetCustomers", c: { }, _f: "Id,Name,Phone", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }
		],
		_fieldsList: [
			/*0*/{ field: "Id", name: "Identify", create: true, edit: true, list: true, type: "bigint",  expandtype:"hidden" },
			/*1*/{ field: "BusinessID", name: "BusinessID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "BusinessID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetBusiness", c: { }, _f: "Id,Name,Phone", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*2*/{ field: "CustomerID", name: "CustomerID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "CustomerID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetCustomers", c: { }, _f: "Id,Name,Phone", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*3*/{ field: "DateCheckIn", name: "DateCheckIn", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*4*/{ field: "DateCheckOut", name: "DateCheckOut", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*5*/{ field: "DateDeliveryInfo", name: "DateDeliveryInfo", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*6*/{ field: "DaySendInfo", name: "DaySendInfo", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*7*/{ field: "RoomInfo", name: "RoomInfo", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*8*/{ field: "PersonReceiveInfo", name: "PersonReceiveInfo", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*9*/{ field: "StatusOrder", name: "StatusOrder", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*10*/{ field: "AnniversaryDay", name: "AnniversaryDay", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*11*/{ field: "RelationInfo", name: "RelationInfo", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*12*/{ field: "OcupationInfo", name: "OcupationInfo", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*13*/{ field: "isActive", name: "isActive", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*14*/{ field: "isValid", name: "isValid", create: false, edit: false, list: false, type: "int",  expandtype:"" },
			/*15*/{ field: "isCreatedDate", name: "isCreateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*16*/{ field: "isUpdatedDate", name: "isUpdateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*17*/{ field: "isPartFull", name: "isPartFull", create: false, edit: false, list: false, type: "string",  expandtype:"" }
		],
		_fieldsReport: [
			/*0*/{ field: "Id", name: "Identify", create: true, edit: true, list: true, type: "bigint",  expandtype:"hidden" },
			/*1*/{ field: "BusinessID", name: "BusinessID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "BusinessID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetBusiness", c: { }, _f: "Id,Name,Phone", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*2*/{ field: "CustomerID", name: "CustomerID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "CustomerID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetCustomers", c: { }, _f: "Id,Name,Phone", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*3*/{ field: "DateCheckIn", name: "DateCheckIn", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*4*/{ field: "DateCheckOut", name: "DateCheckOut", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*5*/{ field: "DateDeliveryInfo", name: "DateDeliveryInfo", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*6*/{ field: "DaySendInfo", name: "DaySendInfo", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*7*/{ field: "RoomInfo", name: "RoomInfo", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*8*/{ field: "PersonReceiveInfo", name: "PersonReceiveInfo", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*9*/{ field: "StatusOrder", name: "StatusOrder", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*10*/{ field: "AnniversaryDay", name: "AnniversaryDay", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*11*/{ field: "RelationInfo", name: "RelationInfo", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*12*/{ field: "OcupationInfo", name: "OcupationInfo", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*13*/{ field: "isActive", name: "isActive", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*14*/{ field: "isValid", name: "isValid", create: false, edit: false, list: false, type: "int",  expandtype:"" },
			/*15*/{ field: "isCreatedDate", name: "isCreateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*16*/{ field: "isUpdatedDate", name: "isUpdateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*17*/{ field: "isPartFull", name: "isPartFull", create: false, edit: false, list: false, type: "string",  expandtype:"" }
		],
		_fieldsSearch: [
			/*0*/{ field: "Id", name: "Identify", create: true, edit: true, list: true, type: "bigint",  expandtype:"hidden" },
			/*1*/{ field: "BusinessID", name: "BusinessID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "BusinessID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetBusiness", c: { }, _f: "Id,Name,Phone", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*2*/{ field: "CustomerID", name: "CustomerID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "CustomerID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetCustomers", c: { }, _f: "Id,Name,Phone", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*3*/{ field: "DateCheckIn", name: "DateCheckIn", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*4*/{ field: "DateCheckOut", name: "DateCheckOut", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*5*/{ field: "DateDeliveryInfo", name: "DateDeliveryInfo", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*6*/{ field: "DaySendInfo", name: "DaySendInfo", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*7*/{ field: "RoomInfo", name: "RoomInfo", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*8*/{ field: "PersonReceiveInfo", name: "PersonReceiveInfo", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*9*/{ field: "StatusOrder", name: "StatusOrder", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*10*/{ field: "AnniversaryDay", name: "AnniversaryDay", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*11*/{ field: "RelationInfo", name: "RelationInfo", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*12*/{ field: "OcupationInfo", name: "OcupationInfo", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*13*/{ field: "isActive", name: "isActive", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*14*/{ field: "isValid", name: "isValid", create: false, edit: false, list: false, type: "int",  expandtype:"" },
			/*15*/{ field: "isCreatedDate", name: "isCreateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*16*/{ field: "isUpdatedDate", name: "isUpdateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*17*/{ field: "isPartFull", name: "isPartFull", create: false, edit: false, list: false, type: "string",  expandtype:"" }
		],
		_editform: [
			{ row: [0, 1], style: [".col-md-2", ".col-md-4"] },
			{ row: [2, 3], style: [".col-md-2", ".col-md-4"] },
			{ row: [4, 5], style: [".col-md-2", ".col-md-4"] },
			{ row: [6, 7], style: [".col-md-2", ".col-md-4"] },
			{ row: [8, 9], style: [".col-md-2", ".col-md-4"] },
			{ row: [10, 11], style: [".col-md-2", ".col-md-4"] },
			{ row: [12, 13], style: [".col-md-2", ".col-md-4"] },
			{ row: [14, 15], style: [".col-md-2", ".col-md-4"] },
			{ row: [16, 17], style: [".col-md-2", ".col-md-4"] },

		],
		_searchform: [
			{ row: [0, 1], style: [".col-md-2", ".col-md-4"] },
			{ row: [2, 3], style: [".col-md-2", ".col-md-4"] },
			{ row: [4, 5], style: [".col-md-2", ".col-md-4"] },
			{ row: [6, 7], style: [".col-md-2", ".col-md-4"] },
			{ row: [8, 9], style: [".col-md-2", ".col-md-4"] },
			{ row: [10, 11], style: [".col-md-2", ".col-md-4"] },
			{ row: [12, 13], style: [".col-md-2", ".col-md-4"] },
			{ row: [14, 15], style: [".col-md-2", ".col-md-4"] },
			{ row: [16, 17], style: [".col-md-2", ".col-md-4"] },

		],
		_updateform: [
			{ row: [0, 1], style: [".col-md-2", ".col-md-4"] },
			{ row: [2, 3], style: [".col-md-2", ".col-md-4"] },
			{ row: [4, 5], style: [".col-md-2", ".col-md-4"] },
			{ row: [6, 7], style: [".col-md-2", ".col-md-4"] },
			{ row: [8, 9], style: [".col-md-2", ".col-md-4"] },
			{ row: [10, 11], style: [".col-md-2", ".col-md-4"] },
			{ row: [12, 13], style: [".col-md-2", ".col-md-4"] },
			{ row: [14, 15], style: [".col-md-2", ".col-md-4"] },
			{ row: [16, 17], style: [".col-md-2", ".col-md-4"] },

		],
	},
	Staff : {
		_rightOnTable: { },
		_titleName: "Staff",
		_id: "Staff",
		_className: "display",
		_listReports: [{}],
		_listSelfTables: [
			{ AjaxObj: { a: "fGetStaff", _f: "*", _gb: "", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" },
			{ AjaxObj: { a: "fGetStaff", _f: "Id,BusinessID,DepartmentID,Name,Avatar,Code,Phone,ortherPhone,Email,Address,Color,isActive,isValid,isCreatedDate,isUpdatedDate,isPartFull", _gb: "", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" },
			{ AjaxObj: { a: "fGetStaff", _f: "Id,BusinessID,DepartmentID,Name,Avatar,Code,Phone,ortherPhone,Email,Address,Color,isActive,isValid,isCreatedDate,isUpdatedDate,isPartFull", _gb: "", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" },
		],
		_listRefTables: [
			{ field: "BusinessID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetBusiness", c: { }, _f: "Id,Name,Phone", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } },
			{ field: "DepartmentID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetDepartment", c: { }, _f: "Id,Name,Phone", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }
		],
		_fieldsList: [
			/*0*/{ field: "Id", name: "Identify", create: true, edit: true, list: true, type: "bigint",  expandtype:"hidden" },
			/*1*/{ field: "BusinessID", name: "BusinessID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "BusinessID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetBusiness", c: { }, _f: "Id,Name,Phone", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*2*/{ field: "DepartmentID", name: "DepartmentID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "DepartmentID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetDepartment", c: { }, _f: "Id,Name,Phone", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*3*/{ field: "Name", name: "Name", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*4*/{ field: "Avatar", name: "Avatar", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*5*/{ field: "Code", name: "Code", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*6*/{ field: "Phone", name: "Phone", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*7*/{ field: "ortherPhone", name: "ortherPhone", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*8*/{ field: "Email", name: "Email", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*9*/{ field: "Address", name: "Address", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*10*/{ field: "Color", name: "Color", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*11*/{ field: "isActive", name: "isActive", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*12*/{ field: "isValid", name: "isValid", create: false, edit: false, list: false, type: "int",  expandtype:"" },
			/*13*/{ field: "isCreatedDate", name: "isCreateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*14*/{ field: "isUpdatedDate", name: "isUpdateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*15*/{ field: "isPartFull", name: "isPartFull", create: false, edit: false, list: false, type: "string",  expandtype:"" }
		],
		_fieldsReport: [
			/*0*/{ field: "Id", name: "Identify", create: true, edit: true, list: true, type: "bigint",  expandtype:"hidden" },
			/*1*/{ field: "BusinessID", name: "BusinessID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "BusinessID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetBusiness", c: { }, _f: "Id,Name,Phone", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*2*/{ field: "DepartmentID", name: "DepartmentID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "DepartmentID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetDepartment", c: { }, _f: "Id,Name,Phone", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*3*/{ field: "Name", name: "Name", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*4*/{ field: "Avatar", name: "Avatar", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*5*/{ field: "Code", name: "Code", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*6*/{ field: "Phone", name: "Phone", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*7*/{ field: "ortherPhone", name: "ortherPhone", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*8*/{ field: "Email", name: "Email", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*9*/{ field: "Address", name: "Address", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*10*/{ field: "Color", name: "Color", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*11*/{ field: "isActive", name: "isActive", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*12*/{ field: "isValid", name: "isValid", create: false, edit: false, list: false, type: "int",  expandtype:"" },
			/*13*/{ field: "isCreatedDate", name: "isCreateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*14*/{ field: "isUpdatedDate", name: "isUpdateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*15*/{ field: "isPartFull", name: "isPartFull", create: false, edit: false, list: false, type: "string",  expandtype:"" }
		],
		_fieldsSearch: [
			/*0*/{ field: "Id", name: "Identify", create: true, edit: true, list: true, type: "bigint",  expandtype:"hidden" },
			/*1*/{ field: "BusinessID", name: "BusinessID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "BusinessID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetBusiness", c: { }, _f: "Id,Name,Phone", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*2*/{ field: "DepartmentID", name: "DepartmentID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "DepartmentID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetDepartment", c: { }, _f: "Id,Name,Phone", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*3*/{ field: "Name", name: "Name", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*4*/{ field: "Avatar", name: "Avatar", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*5*/{ field: "Code", name: "Code", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*6*/{ field: "Phone", name: "Phone", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*7*/{ field: "ortherPhone", name: "ortherPhone", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*8*/{ field: "Email", name: "Email", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*9*/{ field: "Address", name: "Address", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*10*/{ field: "Color", name: "Color", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*11*/{ field: "isActive", name: "isActive", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*12*/{ field: "isValid", name: "isValid", create: false, edit: false, list: false, type: "int",  expandtype:"" },
			/*13*/{ field: "isCreatedDate", name: "isCreateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*14*/{ field: "isUpdatedDate", name: "isUpdateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*15*/{ field: "isPartFull", name: "isPartFull", create: false, edit: false, list: false, type: "string",  expandtype:"" }
		],
		_editform: [
			{ row: [0, 1], style: [".col-md-2", ".col-md-4"] },
			{ row: [2, 3], style: [".col-md-2", ".col-md-4"] },
			{ row: [4, 5], style: [".col-md-2", ".col-md-4"] },
			{ row: [6, 7], style: [".col-md-2", ".col-md-4"] },
			{ row: [8, 9], style: [".col-md-2", ".col-md-4"] },
			{ row: [10, 11], style: [".col-md-2", ".col-md-4"] },
			{ row: [12, 13], style: [".col-md-2", ".col-md-4"] },
			{ row: [14, 15], style: [".col-md-2", ".col-md-4"] },

		],
		_searchform: [
			{ row: [0, 1], style: [".col-md-2", ".col-md-4"] },
			{ row: [2, 3], style: [".col-md-2", ".col-md-4"] },
			{ row: [4, 5], style: [".col-md-2", ".col-md-4"] },
			{ row: [6, 7], style: [".col-md-2", ".col-md-4"] },
			{ row: [8, 9], style: [".col-md-2", ".col-md-4"] },
			{ row: [10, 11], style: [".col-md-2", ".col-md-4"] },
			{ row: [12, 13], style: [".col-md-2", ".col-md-4"] },
			{ row: [14, 15], style: [".col-md-2", ".col-md-4"] },

		],
		_updateform: [
			{ row: [0, 1], style: [".col-md-2", ".col-md-4"] },
			{ row: [2, 3], style: [".col-md-2", ".col-md-4"] },
			{ row: [4, 5], style: [".col-md-2", ".col-md-4"] },
			{ row: [6, 7], style: [".col-md-2", ".col-md-4"] },
			{ row: [8, 9], style: [".col-md-2", ".col-md-4"] },
			{ row: [10, 11], style: [".col-md-2", ".col-md-4"] },
			{ row: [12, 13], style: [".col-md-2", ".col-md-4"] },
			{ row: [14, 15], style: [".col-md-2", ".col-md-4"] },

		],
	},

};
