var _gbSubDictionary = {
	PromotionDetail : {
		_rightOnTable: { },
		_titleName: "PromotionDetail",
		_id: "PromotionDetail",
		_className: "display",
		_listReports: [{}],
		_listSelfTables: [
			{ AjaxObj: { a: "fGetPromotionDetail", _f: "*", _gb: "", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" },
			{ AjaxObj: { a: "fGetPromotionDetail", _f: "Id,PromotionID,WhatOfferName,Discount,MixCustomerType,EmailTitle,BusinessName,OtherDesctiption,PhoneTest,EmailTest,ActiveSTOPfromUer,UseOneTimeThisPromotion,SendNow,Income,DateSendPromotion,UpdatedTime,SaveNextTime,ExpireDate,FromDate,ToDate,DeliverEmail,DeliverSMS,Description,TotalUserUsePromotionSMS,TotalUserUsePromotionEmail,isActive,isValid,isCreatedDate,isUpdatedDate,isPartFull", _gb: "", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" },
			{ AjaxObj: { a: "fGetPromotionDetail", _f: "Id,PromotionID,WhatOfferName,Discount,MixCustomerType,EmailTitle,BusinessName,OtherDesctiption,PhoneTest,EmailTest,ActiveSTOPfromUer,UseOneTimeThisPromotion,SendNow,Income,DateSendPromotion,UpdatedTime,SaveNextTime,ExpireDate,FromDate,ToDate,DeliverEmail,DeliverSMS,Description,TotalUserUsePromotionSMS,TotalUserUsePromotionEmail,isActive,isValid,isCreatedDate,isUpdatedDate,isPartFull", _gb: "", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" },
		],
		_listRefTables: [
			{ field: "PromotionID", mergename: [1], objAjax: { AjaxObj: { a: "fGetPromotions", c: { }, _f: "Id,Id", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }
		],
		_fieldsList: [
			/*0*/{ field: "Id", name: "Identify", create: true, edit: true, list: true, type: "bigint",  expandtype:"hidden" },
			/*1*/{ field: "PromotionID", name: "PromotionID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "PromotionID", mergename: [1], objAjax: { AjaxObj: { a: "fGetPromotions", c: { }, _f: "Id,Id", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*2*/{ field: "WhatOfferName", name: "WhatOfferName", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*3*/{ field: "Discount", name: "Discount", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*4*/{ field: "MixCustomerType", name: "MixCustomerType", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*5*/{ field: "EmailTitle", name: "EmailTitle", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*6*/{ field: "BusinessName", name: "BusinessName", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*7*/{ field: "OtherDesctiption", name: "OtherDesctiption", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*8*/{ field: "PhoneTest", name: "PhoneTest", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*9*/{ field: "EmailTest", name: "EmailTest", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*10*/{ field: "ActiveSTOPfromUer", name: "ActiveSTOPfromUer", create: true, edit: true, list: true, type: "bigint",  expandtype:"" },
			/*11*/{ field: "UseOneTimeThisPromotion", name: "UseOneTimeThisPromotion", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*12*/{ field: "SendNow", name: "SendNow", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*13*/{ field: "Income", name: "Income", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*14*/{ field: "DateSendPromotion", name: "DateSendPromotion", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*15*/{ field: "UpdatedTime", name: "UpdatedTime", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*16*/{ field: "SaveNextTime", name: "SaveNextTime", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*17*/{ field: "ExpireDate", name: "ExpireDate", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*18*/{ field: "FromDate", name: "FromDate", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*19*/{ field: "ToDate", name: "ToDate", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*20*/{ field: "DeliverEmail", name: "DeliverEmail", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*21*/{ field: "DeliverSMS", name: "DeliverSMS", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*22*/{ field: "Description", name: "Description", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*23*/{ field: "TotalUserUsePromotionSMS", name: "TotalUserUsePromotionSMS", create: true, edit: true, list: true, type: "bigint",  expandtype:"" },
			/*24*/{ field: "TotalUserUsePromotionEmail", name: "TotalUserUsePromotionEmail", create: true, edit: true, list: true, type: "bigint",  expandtype:"" },
			/*25*/{ field: "isActive", name: "isActive", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*26*/{ field: "isValid", name: "isValid", create: false, edit: false, list: false, type: "int",  expandtype:"" },
			/*27*/{ field: "isCreatedDate", name: "isCreateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*28*/{ field: "isUpdatedDate", name: "isUpdateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*29*/{ field: "isPartFull", name: "isPartFull", create: false, edit: false, list: false, type: "string",  expandtype:"" }
		],
		_fieldsReport: [
			/*0*/{ field: "Id", name: "Identify", create: true, edit: true, list: true, type: "bigint",  expandtype:"hidden" },
			/*1*/{ field: "PromotionID", name: "PromotionID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "PromotionID", mergename: [1], objAjax: { AjaxObj: { a: "fGetPromotions", c: { }, _f: "Id,Id", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*2*/{ field: "WhatOfferName", name: "WhatOfferName", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*3*/{ field: "Discount", name: "Discount", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*4*/{ field: "MixCustomerType", name: "MixCustomerType", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*5*/{ field: "EmailTitle", name: "EmailTitle", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*6*/{ field: "BusinessName", name: "BusinessName", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*7*/{ field: "OtherDesctiption", name: "OtherDesctiption", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*8*/{ field: "PhoneTest", name: "PhoneTest", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*9*/{ field: "EmailTest", name: "EmailTest", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*10*/{ field: "ActiveSTOPfromUer", name: "ActiveSTOPfromUer", create: true, edit: true, list: true, type: "bigint",  expandtype:"" },
			/*11*/{ field: "UseOneTimeThisPromotion", name: "UseOneTimeThisPromotion", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*12*/{ field: "SendNow", name: "SendNow", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*13*/{ field: "Income", name: "Income", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*14*/{ field: "DateSendPromotion", name: "DateSendPromotion", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*15*/{ field: "UpdatedTime", name: "UpdatedTime", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*16*/{ field: "SaveNextTime", name: "SaveNextTime", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*17*/{ field: "ExpireDate", name: "ExpireDate", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*18*/{ field: "FromDate", name: "FromDate", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*19*/{ field: "ToDate", name: "ToDate", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*20*/{ field: "DeliverEmail", name: "DeliverEmail", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*21*/{ field: "DeliverSMS", name: "DeliverSMS", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*22*/{ field: "Description", name: "Description", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*23*/{ field: "TotalUserUsePromotionSMS", name: "TotalUserUsePromotionSMS", create: true, edit: true, list: true, type: "bigint",  expandtype:"" },
			/*24*/{ field: "TotalUserUsePromotionEmail", name: "TotalUserUsePromotionEmail", create: true, edit: true, list: true, type: "bigint",  expandtype:"" },
			/*25*/{ field: "isActive", name: "isActive", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*26*/{ field: "isValid", name: "isValid", create: false, edit: false, list: false, type: "int",  expandtype:"" },
			/*27*/{ field: "isCreatedDate", name: "isCreateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*28*/{ field: "isUpdatedDate", name: "isUpdateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*29*/{ field: "isPartFull", name: "isPartFull", create: false, edit: false, list: false, type: "string",  expandtype:"" }
		],
		_fieldsSearch: [
			/*0*/{ field: "Id", name: "Identify", create: true, edit: true, list: true, type: "bigint",  expandtype:"hidden" },
			/*1*/{ field: "PromotionID", name: "PromotionID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "PromotionID", mergename: [1], objAjax: { AjaxObj: { a: "fGetPromotions", c: { }, _f: "Id,Id", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*2*/{ field: "WhatOfferName", name: "WhatOfferName", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*3*/{ field: "Discount", name: "Discount", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*4*/{ field: "MixCustomerType", name: "MixCustomerType", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*5*/{ field: "EmailTitle", name: "EmailTitle", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*6*/{ field: "BusinessName", name: "BusinessName", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*7*/{ field: "OtherDesctiption", name: "OtherDesctiption", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*8*/{ field: "PhoneTest", name: "PhoneTest", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*9*/{ field: "EmailTest", name: "EmailTest", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*10*/{ field: "ActiveSTOPfromUer", name: "ActiveSTOPfromUer", create: true, edit: true, list: true, type: "bigint",  expandtype:"" },
			/*11*/{ field: "UseOneTimeThisPromotion", name: "UseOneTimeThisPromotion", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*12*/{ field: "SendNow", name: "SendNow", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*13*/{ field: "Income", name: "Income", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*14*/{ field: "DateSendPromotion", name: "DateSendPromotion", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*15*/{ field: "UpdatedTime", name: "UpdatedTime", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*16*/{ field: "SaveNextTime", name: "SaveNextTime", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*17*/{ field: "ExpireDate", name: "ExpireDate", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*18*/{ field: "FromDate", name: "FromDate", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*19*/{ field: "ToDate", name: "ToDate", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*20*/{ field: "DeliverEmail", name: "DeliverEmail", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*21*/{ field: "DeliverSMS", name: "DeliverSMS", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*22*/{ field: "Description", name: "Description", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*23*/{ field: "TotalUserUsePromotionSMS", name: "TotalUserUsePromotionSMS", create: true, edit: true, list: true, type: "bigint",  expandtype:"" },
			/*24*/{ field: "TotalUserUsePromotionEmail", name: "TotalUserUsePromotionEmail", create: true, edit: true, list: true, type: "bigint",  expandtype:"" },
			/*25*/{ field: "isActive", name: "isActive", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*26*/{ field: "isValid", name: "isValid", create: false, edit: false, list: false, type: "int",  expandtype:"" },
			/*27*/{ field: "isCreatedDate", name: "isCreateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*28*/{ field: "isUpdatedDate", name: "isUpdateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*29*/{ field: "isPartFull", name: "isPartFull", create: false, edit: false, list: false, type: "string",  expandtype:"" }
		],
		_editform: [
			{ row: [0, 1], style: [".col-md-2", ".col-md-4"] },
			{ row: [2, 3], style: [".col-md-2", ".col-md-4"] },
			{ row: [4, 5], style: [".col-md-2", ".col-md-4"] },
			{ row: [6, 7], style: [".col-md-2", ".col-md-4"] },
			{ row: [8, 9], style: [".col-md-2", ".col-md-4"] },
			{ row: [10, 11], style: [".col-md-2", ".col-md-4"] },
			{ row: [12, 13], style: [".col-md-2", ".col-md-4"] },
			{ row: [14, 15], style: [".col-md-2", ".col-md-4"] },
			{ row: [16, 17], style: [".col-md-2", ".col-md-4"] },
			{ row: [18, 19], style: [".col-md-2", ".col-md-4"] },
			{ row: [20, 21], style: [".col-md-2", ".col-md-4"] },
			{ row: [22, 23], style: [".col-md-2", ".col-md-4"] },
			{ row: [24, 25], style: [".col-md-2", ".col-md-4"] },
			{ row: [26, 27], style: [".col-md-2", ".col-md-4"] },
			{ row: [28, 29], style: [".col-md-2", ".col-md-4"] },

		],
		_searchform: [
			{ row: [0, 1], style: [".col-md-2", ".col-md-4"] },
			{ row: [2, 3], style: [".col-md-2", ".col-md-4"] },
			{ row: [4, 5], style: [".col-md-2", ".col-md-4"] },
			{ row: [6, 7], style: [".col-md-2", ".col-md-4"] },
			{ row: [8, 9], style: [".col-md-2", ".col-md-4"] },
			{ row: [10, 11], style: [".col-md-2", ".col-md-4"] },
			{ row: [12, 13], style: [".col-md-2", ".col-md-4"] },
			{ row: [14, 15], style: [".col-md-2", ".col-md-4"] },
			{ row: [16, 17], style: [".col-md-2", ".col-md-4"] },
			{ row: [18, 19], style: [".col-md-2", ".col-md-4"] },
			{ row: [20, 21], style: [".col-md-2", ".col-md-4"] },
			{ row: [22, 23], style: [".col-md-2", ".col-md-4"] },
			{ row: [24, 25], style: [".col-md-2", ".col-md-4"] },
			{ row: [26, 27], style: [".col-md-2", ".col-md-4"] },
			{ row: [28, 29], style: [".col-md-2", ".col-md-4"] },

		],
		_updateform: [
			{ row: [0, 1], style: [".col-md-2", ".col-md-4"] },
			{ row: [2, 3], style: [".col-md-2", ".col-md-4"] },
			{ row: [4, 5], style: [".col-md-2", ".col-md-4"] },
			{ row: [6, 7], style: [".col-md-2", ".col-md-4"] },
			{ row: [8, 9], style: [".col-md-2", ".col-md-4"] },
			{ row: [10, 11], style: [".col-md-2", ".col-md-4"] },
			{ row: [12, 13], style: [".col-md-2", ".col-md-4"] },
			{ row: [14, 15], style: [".col-md-2", ".col-md-4"] },
			{ row: [16, 17], style: [".col-md-2", ".col-md-4"] },
			{ row: [18, 19], style: [".col-md-2", ".col-md-4"] },
			{ row: [20, 21], style: [".col-md-2", ".col-md-4"] },
			{ row: [22, 23], style: [".col-md-2", ".col-md-4"] },
			{ row: [24, 25], style: [".col-md-2", ".col-md-4"] },
			{ row: [26, 27], style: [".col-md-2", ".col-md-4"] },
			{ row: [28, 29], style: [".col-md-2", ".col-md-4"] },

		],
	},
	Promotions : {
		_rightOnTable: { },
		_titleName: "Promotions",
		_id: "Promotions",
		_className: "display",
		_listReports: [{}],
		_listSelfTables: [
			{ AjaxObj: { a: "fGetPromotions", _f: "*", _gb: "", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" },
			{ AjaxObj: { a: "fGetPromotions", _f: "Id,BusinessID,Name,Expense,Income,NumOrderd,DateSent,DateStop,DeliverEmail,DeliverSMS,TotalUserUsePromotionSMS,TotalUserUsePromotionEmail,isActive,isValid,isCreatedDate,isUpdatedDate,isPartFull", _gb: "", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" },
			{ AjaxObj: { a: "fGetPromotions", _f: "Id,BusinessID,Name,Expense,Income,NumOrderd,DateSent,DateStop,DeliverEmail,DeliverSMS,TotalUserUsePromotionSMS,TotalUserUsePromotionEmail,isActive,isValid,isCreatedDate,isUpdatedDate,isPartFull", _gb: "", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" },
		],
		_listRefTables: [
			{ field: "BusinessID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetBusiness", c: { }, _f: "Id,Name,Phone", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }
		],
		_fieldsList: [
			/*0*/{ field: "Id", name: "Identify", create: true, edit: true, list: true, type: "bigint",  expandtype:"hidden" },
			/*1*/{ field: "BusinessID", name: "BusinessID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "BusinessID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetBusiness", c: { }, _f: "Id,Name,Phone", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*2*/{ field: "Name", name: "Name", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*3*/{ field: "Expense", name: "Expense", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*4*/{ field: "Income", name: "Income", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*5*/{ field: "NumOrderd", name: "NumOrderd", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*6*/{ field: "DateSent", name: "DateSent", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*7*/{ field: "DateStop", name: "DateStop", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*8*/{ field: "DeliverEmail", name: "DeliverEmail", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*9*/{ field: "DeliverSMS", name: "DeliverSMS", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*10*/{ field: "TotalUserUsePromotionSMS", name: "TotalUserUsePromotionSMS", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*11*/{ field: "TotalUserUsePromotionEmail", name: "TotalUserUsePromotionEmail", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*12*/{ field: "isActive", name: "isActive", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*13*/{ field: "isValid", name: "isValid", create: false, edit: false, list: false, type: "int",  expandtype:"" },
			/*14*/{ field: "isCreatedDate", name: "isCreateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*15*/{ field: "isUpdatedDate", name: "isUpdateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*16*/{ field: "isPartFull", name: "isPartFull", create: false, edit: false, list: false, type: "string",  expandtype:"" }
		],
		_fieldsReport: [
			/*0*/{ field: "Id", name: "Identify", create: true, edit: true, list: true, type: "bigint",  expandtype:"hidden" },
			/*1*/{ field: "BusinessID", name: "BusinessID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "BusinessID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetBusiness", c: { }, _f: "Id,Name,Phone", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*2*/{ field: "Name", name: "Name", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*3*/{ field: "Expense", name: "Expense", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*4*/{ field: "Income", name: "Income", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*5*/{ field: "NumOrderd", name: "NumOrderd", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*6*/{ field: "DateSent", name: "DateSent", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*7*/{ field: "DateStop", name: "DateStop", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*8*/{ field: "DeliverEmail", name: "DeliverEmail", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*9*/{ field: "DeliverSMS", name: "DeliverSMS", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*10*/{ field: "TotalUserUsePromotionSMS", name: "TotalUserUsePromotionSMS", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*11*/{ field: "TotalUserUsePromotionEmail", name: "TotalUserUsePromotionEmail", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*12*/{ field: "isActive", name: "isActive", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*13*/{ field: "isValid", name: "isValid", create: false, edit: false, list: false, type: "int",  expandtype:"" },
			/*14*/{ field: "isCreatedDate", name: "isCreateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*15*/{ field: "isUpdatedDate", name: "isUpdateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*16*/{ field: "isPartFull", name: "isPartFull", create: false, edit: false, list: false, type: "string",  expandtype:"" }
		],
		_fieldsSearch: [
			/*0*/{ field: "Id", name: "Identify", create: true, edit: true, list: true, type: "bigint",  expandtype:"hidden" },
			/*1*/{ field: "BusinessID", name: "BusinessID", create: true, edit: true, list: true, type: "bigint",  expandtype:"select" , fkey:{obj:"undefined", fcol:"undefined}"}, option:{ field: "BusinessID", mergename: [1,2], objAjax: { AjaxObj: { a: "fGetBusiness", c: { }, _f: "Id,Name,Phone", ModelDb: "AppCoreDb" }, APIkey: "kUcHUoWsxLPrIJy$rTcbeG5k" } }},
			/*2*/{ field: "Name", name: "Name", create: true, edit: true, list: true, type: "string",  expandtype:"" },
			/*3*/{ field: "Expense", name: "Expense", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*4*/{ field: "Income", name: "Income", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*5*/{ field: "NumOrderd", name: "NumOrderd", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*6*/{ field: "DateSent", name: "DateSent", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*7*/{ field: "DateStop", name: "DateStop", create: true, edit: true, list: true, type: "datetime",  expandtype:"" },
			/*8*/{ field: "DeliverEmail", name: "DeliverEmail", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*9*/{ field: "DeliverSMS", name: "DeliverSMS", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*10*/{ field: "TotalUserUsePromotionSMS", name: "TotalUserUsePromotionSMS", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*11*/{ field: "TotalUserUsePromotionEmail", name: "TotalUserUsePromotionEmail", create: true, edit: true, list: true, type: "double",  expandtype:"" },
			/*12*/{ field: "isActive", name: "isActive", create: true, edit: true, list: true, type: "int",  expandtype:"" },
			/*13*/{ field: "isValid", name: "isValid", create: false, edit: false, list: false, type: "int",  expandtype:"" },
			/*14*/{ field: "isCreatedDate", name: "isCreateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*15*/{ field: "isUpdatedDate", name: "isUpdateDated", create: false, edit: false, list: false, type: "datetime",  expandtype:"" },
			/*16*/{ field: "isPartFull", name: "isPartFull", create: false, edit: false, list: false, type: "string",  expandtype:"" }
		],
		_editform: [
			{ row: [0, 1], style: [".col-md-2", ".col-md-4"] },
			{ row: [2, 3], style: [".col-md-2", ".col-md-4"] },
			{ row: [4, 5], style: [".col-md-2", ".col-md-4"] },
			{ row: [6, 7], style: [".col-md-2", ".col-md-4"] },
			{ row: [8, 9], style: [".col-md-2", ".col-md-4"] },
			{ row: [10, 11], style: [".col-md-2", ".col-md-4"] },
			{ row: [12, 13], style: [".col-md-2", ".col-md-4"] },
			{ row: [14, 15], style: [".col-md-2", ".col-md-4"] },
			{ row: [16], style: [".col-md-2"] }
		],
		_searchform: [
			{ row: [0, 1], style: [".col-md-2", ".col-md-4"] },
			{ row: [2, 3], style: [".col-md-2", ".col-md-4"] },
			{ row: [4, 5], style: [".col-md-2", ".col-md-4"] },
			{ row: [6, 7], style: [".col-md-2", ".col-md-4"] },
			{ row: [8, 9], style: [".col-md-2", ".col-md-4"] },
			{ row: [10, 11], style: [".col-md-2", ".col-md-4"] },
			{ row: [12, 13], style: [".col-md-2", ".col-md-4"] },
			{ row: [14, 15], style: [".col-md-2", ".col-md-4"] },
			{ row: [16], style: [".col-md-2"] }
		],
		_updateform: [
			{ row: [0, 1], style: [".col-md-2", ".col-md-4"] },
			{ row: [2, 3], style: [".col-md-2", ".col-md-4"] },
			{ row: [4, 5], style: [".col-md-2", ".col-md-4"] },
			{ row: [6, 7], style: [".col-md-2", ".col-md-4"] },
			{ row: [8, 9], style: [".col-md-2", ".col-md-4"] },
			{ row: [10, 11], style: [".col-md-2", ".col-md-4"] },
			{ row: [12, 13], style: [".col-md-2", ".col-md-4"] },
			{ row: [14, 15], style: [".col-md-2", ".col-md-4"] },
			{ row: [16], style: [".col-md-2"] }
		],
	},

};
